
int bitXor(int, int);
int test_bitXor(int, int);
int getByte(int, int);
int test_getByte(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int bang(int);
int test_bang(int);
int bitCount(int);
int test_bitCount(int);
int tmin();
int test_tmin();
int fitsBits(int, int);
int test_fitsBits(int, int);
int isNegative(int);
int test_isNegative(int);
int rempwr2(int, int);
int test_rempwr2(int, int);
int absVal(int);
int test_absVal(int);
int trueFiveEighths(int);
int test_trueFiveEighths(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
